sudo: required
services:
  - docker

addons:
  sauce_connect: true

cache:
  docker: true
  directories:
#    - modules/admin/node_modules
    - modules/admin/src/bower_components
    - .autoconf
    - $HOME/.m2

language: java

jdk:
  - oraclejdk8

node_js:
  - "5"

before_install:
  - nvm install 6
  - nvm use 6

install:
  - cd modules/admin/ && npm install && cd src && ../node_modules/bower/bin/bower install && cd ..

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm run start:dev&
  - sleep 10

after_success:
  - mvn clean cobertura:cobertura coveralls:report

script:
  - npm run test
  - npm run e2e

notifications:
  email:
    recipients:
      - info@smsc.io
      - dimakuba124@gmail.com
    on_success: change
    on_failure: always