sudo: required
services:
  - docker

language: node_js
node_js:
  - "0.10"
before_install:
  - docker pull orientdb
  - docker run -d --name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=rootpwd orientdb:latest
install:
  - cd modules/admin/ && npm install && cd src && ../node_modules/bower/bin/bower install
script: cd .. && npm run test && npm run e2e