sudo: required
services:
  - docker

addons:
  sonarqube: true

addons:
apt:
  packages:
    - oracle-java8-installer
    - maven

cache:
  yarn: true
  docker: true
  directories:
    - modules/admin/node_modules
    - modules/admin/typings
    - .autoconf
    - $HOME/.m2

language: java

jdk:
  - oraclejdk8

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - nvm install 6
  - nvm use 6

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push smscio/smsc;
    fi
  - mvn clean -DrepoToken=$COVERALLS_REPO_TOKEN cobertura:cobertura coveralls:report

script:
  - ./bin/deploy.sh

notifications:
  email:
    recipients:
      - info@smsc.io
      - dimakuba124@gmail.com
      - nazar.lipkovskyy@gmail.com
    on_success: always
    on_failure: always

addons:
  sonarqube: true
  sauce_connect: true
