sudo: required
services:
  - docker

addons:
apt:
  packages:
    - oracle-java8-installer
    - maven

cache:
  bundler: true
  yarn: true
  docker: true
  directories:
    - modules/admin/node_modules
    - .autoconf
    - $HOME/.m2
    - $HOME/docker

language: java
install: true

jdk:
  - oraclejdk8

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - nvm install 7
  - nvm use 7
  - npm install -g yarn

script:
  - ./bin/build.sh

after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - ./bin/deploy.sh

before_cache:
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

after_deploy:
  - ./bin/report.sh

notifications:
  email:
    recipients:
      - info@smsc.io
      - dimakuba124@gmail.com
      - nazar.lipkovskyy@gmail.com
    on_success: always
    on_failure: always

addons:
  sonarqube: true
  sauce_connect: true
