sudo: required
services:
  - docker

addons:
apt:
  packages:
    - oracle-java8-installer
    - maven

cache:
  bundler: true
  yarn: true
  docker: true
  directories:
    - modules/admin/node_modules
    - .autoconf
    - $HOME/.m2
    - $HOME/docker

language: java
install: true

jdk:
  - oraclejdk8

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - nvm install 7
  - nvm use 7

script:
  - ./bin/build.sh

after_success:
  - ./bin/deploy.sh
  - ./bin/report.sh
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "Eo4CmDoNjsl8Wjwby7+HEPMPYIm7wi434vNbABsIWMP1PXFugy7V+9hyPSVynA+dRTGMOquL0DG34xRIUOohrBquZxx7xc6zzhBFrLt4I6LqbQpaG5ZpR5dYmuRY3bQEjNtt8N1juxdJjivUDVr88IklHTnyLGYIHr92K3/HRQxh3+61gFP+qVEZUOrk4CClN00kPJvm9s1B/OQPacwLkTRp2OtoitkNfLmSOk1t4LjBi8Yy8IfVqERogPKqdLPYHl1GnsTCLK0A7mg3XZpPZ3iIRpRyIBCxcQ7JIpz29Y2VB0CHNaJnkn37RXl0HWM+WqROrKPPVdk2ZWbvsqKdaH3ncJkd1Uz7uhTRAOuQmsQMbH50AbBLa3puOokpwwBeyQh+gjsmEbq0ZVk0BWyJS/S03QkM3zrUdAwOynXEB6X5EVpBqAcckdHZUt/pXFQj1HtG3/D6WqQrNhKB2o/7YfqK2gsQ6ewDXHz8m+KuoxbEl21ATrUnVRK37o16tGpPlQ+eFJrz56LZu8zb6ZJn4PaOiPSKqT0j0GJpBz21s/cEuB5lqNSPn/gjNJtQGrTBLtqkiDP6lLxGNoedPX1DpmR8F9n06dm/5LGmA8jKaLfBFVLbQUdDtnMXKE8hxEBNLUdnC8bChs7WNWQUTApdi4Wi897qrt7Io4IXJc9WQ1o="
  file:
    - "modules/core/target/smsc.jar"
  on:
    branch: master

notifications:
  email:
    recipients:
      - info@smsc.io
      - dimakuba124@gmail.com
      - nazar.lipkovskyy@gmail.com
    on_success: always
    on_failure: always

addons:
  srcclr: true
  sonarqube: true
  sauce_connect: true
