sudo: required
services:
  - docker

addons:
apt:
  packages:
    - oracle-java8-installer
    - maven

cache:
  bundler: true
  yarn: true
  docker: true
  directories:
    - modules/admin/node_modules
    - .autoconf
    - $HOME/.m2
    - $HOME/docker

language: java
install: true

jdk:
  - oraclejdk8

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - nvm install 7
  - nvm use 7

script:
  - ./bin/build.sh

after_success:
  - ./bin/deploy.sh
  
after_deploy:
  - ./bin/report.sh
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: F6CCxY9W3dCmtDhXVUls/6TZUe1v6TYH6PCr4PoRmECw7hBcpEwaWOSjAWc8gQZGDRmcjYsBH9qHN8RhBB76Aub9z+pQEV5HonqxqXRo/SFD5TMMZE66hcM2mKRBeAnKicckVigGpn7OwjuMqUjbFlff9HtGDvX/h0WX6f3qFHJwVMXjfA8jO+SzJ1rl+d/3/aeWVUu+WJt1Ty0gIMyzRe3iNqm17tQC/Ne66lsZtwqEOf+8Cb5CfpLRz834GMfu5oOCU3SssNEM0MldKhJza0lEP7vu/VJFvcEbgKalbTQw+bq00olq60g2/B8ldyA9+9hIzw1WHh36729Tx31DnUSdSqEn5mYmtwc0BNdJZm5UTV1jnJDrvWN5XoGgJqvoyDtiefAMTPcYMHShooUlMhblFoyJOjZFqmWTP04nq8p+rfs8ZHjTH5iG5Uu5M/quzRGYE4TaxcJyDCWoW4bwnc0VzgdD5vY2weHIA31I+8KEaknhQhDsMIobICup+G8bNqvIKLIWINraZxJBQL1nGy7EV/ghJ/6OPb77pY17UIrnHB/+k10g6xzcJX2wojAgGdmAAhV4WsiW/S/KQ2rCto5iBnmh7X1qUaNE5ZVEO1XGvJrTAna821EfNrIOyTuCz2yqs7F0h6v2w6h7yYpRam/I8hhzgv4pFrtlWnpKgRs=
  file: modules/core/target/smsc.jar
  on:
    repo: bulktrade/SMSC
    branch: master

notifications:
  email:
    recipients:
      - info@smsc.io
      - dimakuba124@gmail.com
      - nazar.lipkovskyy@gmail.com
    on_success: always
    on_failure: always

addons:
  srcclr: true
  sonarqube: true
  sauce_connect: true
