sudo: required
services:
  - docker

addons:
  sauce_connect: true

cache:
  docker: true
  directories:
    - modules/admin/node_modules
    - modules/admin/src/bower_components
    - .autoconf
    - $HOME/.m2

language: node_js
node_js:
  - "4"
install:
  - cd modules/admin/ && npm install && cd src && ../node_modules/bower/bin/bower install && cd ..
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm run start:dev&
  - sleep 30
script:
  - npm run test
  - npm run e2e