sudo: required
services:
  - docker

addons:
  sauce_connect: true

cache:
  docker: true
  directories:
    - modules/admin/node_modules
    - modules/admin/src/bower_components

language: node_js
node_js:
  - "4"
before_install:
  - docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
  - docker run -d --name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=123test -e VIRTUAL_HOST=orientdb.* -e VIRTUAL_PORT=2480 orientdb:latest
  - docker exec -it orientdb /orientdb/bin/console.sh "CREATE DATABASE memory:smsc admin admin MEMORY DOCUMENT;"
install:
  - cd modules/admin/ && npm install && cd src && ../node_modules/bower/bin/bower install && cd ..
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm run test
  - npm run protractor