sudo: required
services:
  - docker

addons:
apt:
  packages:
    - oracle-java8-installer
    - maven

cache:
  yarn: true
  docker: true
  directories:
    - modules/admin/node_modules
    - .autoconf
    - $HOME/.m2

language: java
install: true

jdk:
  - oraclejdk8

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - nvm install 7
  - nvm use 7
  - npm install -g yarn versioneye-update

script:
  - ./bin/deploy.sh

notifications:
  email:
    recipients:
      - info@smsc.io
      - dimakuba124@gmail.com
      - nazar.lipkovskyy@gmail.com
    on_success: always
    on_failure: always

addons:
  sonarqube: true
  sauce_connect: true
